import Foundation

/// Secondary, event-driven source with official numbers — only flows while
/// Claude Code is actually running. A small statusline shell script (installed
/// on demand from the menu) appends each statusline JSON payload to
/// ~/.claude/usage-mascot.json; this class file-watches it and feeds the
/// freshest sample into the store. Canonical payload shape:
///
///   { "rate_limits": { "five_hour": { "used_percentage": 42, "resets_at": 1742651200 },
///                      "seven_day": { "used_percentage": 18, "resets_at": 1743120000 } } }
///
/// `resets_at` here is epoch seconds; the OAuth endpoint may use ISO-8601 —
/// JSONProbe normalizes both.
final class StatuslineBridge {

    private let store: UsageStore
    private var dirSource: DispatchSourceFileSystemObject?
    private var fallbackTimer: Timer?
    private var lastMTime: Date = .distantPast

    let claudeDir = (NSHomeDirectory() as NSString).appendingPathComponent(".claude")
    var bridgeFilePath: String { (claudeDir as NSString).appendingPathComponent("usage-mascot.json") }
    var scriptPath: String { (claudeDir as NSString).appendingPathComponent("pip-statusline.sh") }
    var settingsPath: String { (claudeDir as NSString).appendingPathComponent("settings.json") }

    init(store: UsageStore) {
        self.store = store
    }

    func start() {
        attachWatcher()
        // Fallback: cheap mtime check, and re-attach if ~/.claude appears later.
        let t = Timer(timeInterval: 5, repeats: true) { [weak self] _ in
            guard let self else { return }
            if self.dirSource == nil { self.attachWatcher() }
            self.checkFile()
        }
        t.tolerance = 2
        RunLoop.main.add(t, forMode: .common)
        fallbackTimer = t
        checkFile()
    }

    var isInstalled: Bool {
        FileManager.default.fileExists(atPath: scriptPath)
    }

    // MARK: - Watching

    private func attachWatcher() {
        let fd = open(claudeDir, O_EVTONLY)
        guard fd >= 0 else { return }
        let source = DispatchSource.makeFileSystemObjectSource(
            fileDescriptor: fd, eventMask: [.write], queue: .main)
        source.setEventHandler { [weak self] in self?.checkFile() }
        source.setCancelHandler { close(fd) }
        source.resume()
        dirSource = source
    }

    private func checkFile() {
        let fm = FileManager.default
        guard let attrs = try? fm.attributesOfItem(atPath: bridgeFilePath),
              let mtime = attrs[.modificationDate] as? Date,
              mtime > lastMTime else { return }
        lastMTime = mtime
        guard let content = try? String(contentsOfFile: bridgeFilePath, encoding: .utf8) else { return }
        // Newest entry is the last parseable line.
        for line in content.split(separator: "\n").reversed() {
            let trimmed = line.trimmingCharacters(in: .whitespaces)
            guard !trimmed.isEmpty, let data = trimmed.data(using: .utf8),
                  let object = JSONProbe.parse(data),
                  var snap = JSONProbe.extractUsage(from: object) else { continue }
            snap.lastUpdated = mtime
            store.ingest(snap, source: "statusline")
            return
        }
    }

    // MARK: - Installer

    /// Writes the bridge script and points Claude Code's statusLine setting at
    /// it (backing up settings.json first). If a statusline command is already
    /// configured, the script chains to it so the existing statusline keeps
    /// rendering. Returns a human-readable summary.
    func install() throws -> String {
        let fm = FileManager.default
        try fm.createDirectory(atPath: claudeDir, withIntermediateDirectories: true)

        var settings: [String: Any] = [:]
        if let data = fm.contents(atPath: settingsPath),
           let object = JSONProbe.parse(data) as? [String: Any] {
            settings = object
        }
        var originalCommand: String?
        if let sl = settings["statusLine"] as? [String: Any],
           let cmd = sl["command"] as? String,
           cmd != scriptPath {
            originalCommand = cmd
        }

        var script = """
        #!/bin/sh
        # Generated by \(mascotName) — feeds Claude Code statusline JSON to the desktop mascot.
        # Claude Code pipes a JSON payload (including rate_limits) to this script's stdin.
        INPUT=$(cat)
        FILE="$HOME/.claude/usage-mascot.json"
        printf '%s\\n' "$INPUT" >> "$FILE"
        # keep the file from growing forever
        if [ "$(wc -l < "$FILE" | tr -d ' ')" -gt 200 ]; then
          tail -n 50 "$FILE" > "$FILE.tmp" && mv "$FILE.tmp" "$FILE"
        fi

        """
        if let original = originalCommand {
            script += "# chain to the statusline that was configured before \(mascotName) was installed\n"
            script += "printf '%s\\n' \"$INPUT\" | \(original)\n"
        } else {
            script += "echo \"🐾 \(mascotName.lowercased()) is watching\"\n"
        }

        try script.write(toFile: scriptPath, atomically: true, encoding: .utf8)
        try fm.setAttributes([.posixPermissions: 0o755], ofItemAtPath: scriptPath)

        if fm.fileExists(atPath: settingsPath) {
            let backup = settingsPath + ".pip-backup"
            if fm.fileExists(atPath: backup) { try? fm.removeItem(atPath: backup) }
            try? fm.copyItem(atPath: settingsPath, toPath: backup)
        }
        settings["statusLine"] = ["type": "command", "command": scriptPath]
        let data = try JSONSerialization.data(
            withJSONObject: settings, options: [.prettyPrinted, .sortedKeys])
        try data.write(to: URL(fileURLWithPath: settingsPath))

        var message = "installed.\n\nscript: \(scriptPath)\nclaude code settings updated"
        if fm.fileExists(atPath: settingsPath + ".pip-backup") {
            message += " (backup at settings.json.pip-backup)"
        }
        if originalCommand != nil {
            message += "\nyour existing statusline command is chained, so it keeps working."
        }
        message += "\n\nofficial numbers will flow in whenever claude code is running."
        return message
    }
}
